server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&timezone=shanghai
    username: root
    password: root
mybatis:
  type-aliases-package: com.fan.entity
  mapper-locations: classpath:mapper/*.xml
